### ISSUE TITLE
dci-agent rpm is broken on RHEL7

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-agent#1]
dci-agent rpm is broken on RHEL7:

```
[root@dci-agent0 ~]# dci-agent 
Traceback (most recent call last):
  File "/usr/bin/dci-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 601, in resolve
    requirements = list(requirements)[::-1]  # set up the stack
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2839, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2807, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'dci-agent===0.0.201610111707git36ff2e6', 'at', '===0.0.201610111707git36ff2e6')
[root@dci-agent0 ~]# rpm -q dci-agent
dci-agent-0.0.201610111707git36ff2e6-1.el7.centos.noarch
```

**Comment by Spredzy** [comment]
This is because `python-setuptools` isn't installed with the proper version. A proper version has been made available in `dci-extras` repos. Please try and let me know.
